# Generated by Django 2.2.6 on 2019-11-25 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videofeed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideorecommendation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youtubevideorecommendation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='youtubevideorecommendationshare',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youtubevideorecommendationshare',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
